### ISSUE TITLE
Descriptive metadata bulk upload interface

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/Access-Platform#113]
An interface that accepts descriptive metadata files, uploads them to newly created `dmdtask` documents, and causes the right background processes to run.

A front-end proof of concept exists in sapindale, but will likely need to be updated to conform to changes in #111. A lot of this should be integrated into accessor as well.

**Comment by RussellMcOrmond** [comment]
A [document was written](https://crkn.sharepoint.com/:w:/s/platform/EW2AmkBTXZZEnwWWSAsIHDcBlRWSAYf9gL3oKPrvr4EU0A?e=vIIbN2) in August 2020 to describe the thinking at the time.  What we are doing is simpler than that, as we don't need a complex API to carry out this simple task.


* multi-record file format uploaded (format needs to contain an ID in record) from web interface
* back-end process splits multi-record format into separate validated XML records, storing details in Couch document
* Web interface used to confirm ID's, and pick subset to be loaded.
* back-end would copy the XML files to the right place.


A very basic demonstration of the upload form was already added to Sapindale, which can be ported or at least used as inspiration #55

**Comment by RussellMcOrmond** [comment]
https://github.com/crkn-rcdr/sapindale/issues/97  provides additional description, but given that ticket is in the context of Sapindale it can now be closed.

**Comment by RussellMcOrmond** [comment]
I uploaded the 3 .mrc files that are in [Sample Metadata](https://crkn.sharepoint.com/:f:/r/sites/platform/Shared%20Documents/Development%20-%20Current%20Projects/Access%20Platform1/Sample%20Metadata?csf=1&web=1&e=EctkHu) so far to the production database (View via Iris).

Using the `dmd-task-swift` branch, and running `pnpm prod` pointing to the production database..


https://access-dev.canadiana.ca/dmd/517ee635a2305bc78b58b9efc1264a07

It was success with 0 items, not what I expected. I forgot which one this was -- There is a file that I hadn't tested yet, so I'm guessing it was that one.

* A new feature I suspect would be useful is to store the filename of the file that was uploaded, so the operator will know which metadata file they are looking at the results for.  Some of these may be long running processes, and there may be more than one tab open waiting for results.


Next is https://access-dev.canadiana.ca/dmd/517ee635a2305bc78b58b9efc126723a which on the browser just says "Loading...", but there is an error message in a 500 error from the server-side of Access ("invalid_union", etc).
(This has 3104 records.  Some records have messages, but they all parsed and validated).


Similar with https://access-dev.canadiana.ca/dmd/517ee635a2305bc78b58b9efc1265540
(This is a single record, ID is unknown because of an error in the file)



I'm guessing from the output (I don't know Zod/etc).  It seems like the https://github.com/crkn-rcdr/Access-Platform/blob/main/packages/data/src/util/ProcessUpdate.ts is missing `requestDate` in ProcessResult.  That field exists for both a request and a result -- it doesn't go away, and may even be useful to display.

**Comment by RussellMcOrmond** [comment]
I have left #112 open but unassigned as I'm wanting to wait until the metadata team have evaluated it, which is based on this web interface being in production available to them to try out.  Once we have received some feedback, we can close both.
