### ISSUE TITLE
Hooking up admin tools to the noid service for creating new objects in the editor

### ISSUE THREAD

**Issue by brittnylapierre** [crkn-rcdr/Access-Platform#191]
Hey @SaschaAdler do you have any ideas on how best to structure the code around this? (what service or package should the call to the noid service go, ands any other implementation details/thoughts)

**Comment by SaschaAdler** [comment]
This is going to be something done through lapin, which should be made aware of the noid service.

@RussellMcOrmond Should we use the production noid service even when testing this out in development, or a) should I incorporate a dev noid service into the dev environment b) should we come up with a mock noid service for development? I know we're not going to run out of noids if we use real ones for fake purposes. :)

**Comment by RussellMcOrmond** [comment]
Interesting -- Brittny brought this up in our check-in, so you and she were thinking about it at the same time.

b)  We should have a dev noid service.  Not sure why a mock noid service, when the real one can be pulled in and used?  If the issue is our Docker Registry being behind the VPN, we can contemplate whether https://github.com/crkn-rcdr/noid should be put up on Docker Hub?
