### ISSUE TITLE
`dmdtask` schema updates

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/Access-Platform#232]
See discussion in #230.

---

- Remove references to `store` processes as lapin will take care of that
- Remove the `prefix` field, as the interface will be configured to look up with a prefix after the split.
- Make `id` optional in `SplitRecord`, in case the reason the result isn't valid is that an id couldn't be extracted.

**Comment by RussellMcOrmond** [comment]
* Splitting a multi-record file into individual records is separate from anything specific to a record.  Simplest example is a CSV file, where each line can be thought of as separate than previous lines.
* each individual record can be missing an identifier, or fail XML validation, or generate errors/warnings during flatten.  The current tool just dies as soon as there is any problem, but it would be an improvement to continue running and display all the records that had issues (so staff can fix them all at once, rather than one at a time).
* The concept of "valid" and "invalid" on a per-record basic is a bit vague as there are many reasons to declare one way or the other that isn't covered by XML validation successful and CIHM::Meta::dmd::flatten successful.  I'd prefer any fine-tuning of that definition, and how to communicate with the user, be kept in the more actively maintained code in Access-Platform than in the Perl.  The dumber the Perl, the smarter the overall application can be.
* I have no idea what "If not, why not split them when we process the file?".  Hopefully the Perl code only runs once, and take the uploaded file and generates multiple XML/JSON files.  What is done after that, and in what stages, shouldn't require the Perl to ever run again.
* This relates to pushing complexity into the PERL that would be better off in a UI that can do different things at different improvement stages of the tool.  Having the Perl output an ugly text message into the messages string doesn't at all seem as useful as that check for duplicate IDs happening in the Web interface that can then display the duplicates in a useful way.  Again, the dumber the Perl the better the App as far as I'm concerned -- put the vast majority of the business logic in Lapin and/or Access.

**Comment by SaschaAdler** [comment]
Eh, the more I think about this, the more I don't think we need to separate valid and invalid items in the admin tool. I'll amend the discussion item with that.

For the record, though, my suggestions weren't about business logic so much as the data structure that the Perl tool outputs. There's no difference in business logic between

```json
{
  "items": [
    { 
      "id": "foo",
      "valid": true,
      "message": "good job"
    },
    { 
      "id": "bar",
      "valid": false,
      "message": "something blew up!"
    }
  ]
}
```

and

```json
{
  "validItems": {
    "foo": "good job"
  },
  "invalidItems": {
    "bar": "something blew up!"
  }
}
```

although if we want to maintain the order of the records we get we should keep using an array.

The one exception re: business logic is in detecting duplicate ids. What happens if/when that happens, and what should happen?

**Comment by SaschaAdler** [comment]
>     * each individual record can be missing an identifier, or fail XML validation, or generate errors/warnings during flatten.  The current tool just dies as soon as there is any problem, but it would be an improvement to continue running and display all the records that had issues (so staff can fix them all at once, rather than one at a time).

How do we know how to display a record that had an issue if it doesn't have an identifier? (Seems to me that the answer to whether or not `id` can be undefined is yes.)

**Comment by RussellMcOrmond** [comment]
How about this as a suggestion.  Instead of the field being called "valid", we use a different name like XMLValid to remind the developer of the specific meaning of the boolean we are using in that field?


* We convert CSV, DB/Text dumps and MARC Transit (binary) files to XML.  Problems like we said CSV but sent up an XML file would show up in the split process request message.

* We then do an XML validation of the individual generated XML files, any of which might individually fail.  Warnings and messages end up in items[].message, and if a die() happened then valid will be false and processing for that record stopped.
* We then do CIHM::Meta::dmd::flatten() on the XML. Warnings end up appended in the same items[].message, and if a die() happened then valid will be false and processing for that record stopped.

BTW: I'm never quite sure if I'm reading https://github.com/crkn-rcdr/Access-Platform/blob/main/packages/data/src/dmd/Task.ts correctly.  It isn't the easiest format for humans to read :-)

**Comment by RussellMcOrmond** [comment]
"Seems to me that the answer to whether or not id can be undefined is yes."

Agreed.

Example of a "warning" for a CSV file missing an ID. In this case no XML is generated, just skip to next line.
https://github.com/crkn-rcdr/CIHM-METS-App/blob/master/lib/CIHM/METS/App/csv2dc.pm#L54


Marc is also a warning (also don't generate XML, just skip that record).
https://github.com/crkn-rcdr/CIHM-METS-App/blob/master/lib/CIHM/METS/App/Marc.pm#L92-L95

**Comment by SaschaAdler** [comment]
I went with `parsed` instead of `valid`, since that's what the tool is doing.
