### ISSUE TITLE
Create lapin requests required for completing descriptive metadata updates

### ISSUE THREAD

**Issue by brittnylapierre** [crkn-rcdr/Access-Platform#259]
### Lapin route: `dmdtask.fetchResult`

Input:

```ts
type FetchInput = {
  task: string; // dmdtask uuid
  index: number; // array index of the item you want to fetch
  type: "xml" | "json"; // type of attachment to return
};
```

Todo:
- [x] The attachments  for successfully processed items are named after the item's index in the items array. So if items[0] was parsed successfully, there will be attachments [on the dmdTask] called 0.json and 0.xml. Grab the [index].json attachment using the dmdtask handler's getAttachment method. 
- [x] Decode the json 
- [x] Display the json to the user

### Lapin route: `dmdtask.storeAccess`

Input:

```ts
type StoreAccessInput = {
  task: string; // dmdtask uuid
  index: number; // array index of item whose metadata is being stored
  slug: string; // prefix + id (we might not need this if we send the resolved noid)
  noid: string; // result of slug lookup
};
```
Todo:
- [x] Looks up the task  
- [x] Get the attachment [index].xml from the dmdtask document (using the dmdtask handler's getAttachment method) and;
- [x] Get the [label] corresponding to item[index],
- [x] Get the [noid] and [type] of the access object using the [slug] paramter.
- [x] Successfully parsed items will have a field called output which can have the values marc, dc, or issueinfo. Determine the correct filename of the attachment using [output] and [noid].  The relevant possible filenames here are dmdMARC.xml, dmdDC.xml, and dmdISSUEINFO.xml. (ex: 69429/[noid]/dmdMARC.xml)
- [x] Then, use swift.accessMetadata.putObject to send it to Swift with the object name and content-type application/xml.
- [x] Then, update the access objects label to the label corresponding to item[index]. Use access.editCollection or access.editManifest depending on [type] to update the object with the following:
`{
  "label": { "none": "The name of the thing" }
}`
- [x] updateInternalMeta is being set by editCollection/editManifest

### Lapin route: `dmdtask.storePreservation`

Input:

```ts
type StorePreservationInput = {
  task: string; // dmdtask uuid
  index: number;
  slug: string;
};
```

Todo:
- [x] Create a handler for the wipmeta database, Sascha can help with the handler when he gets back.
- [x] look up items from preservation
- [x] store metadata in preservation
- [x] update must be a str timestamp
- [x] create a change label design doc and use it after store to update label in wipmeta
- [x] won't need more than one view, so you can include all the code you need within the single view and not have a prelude at all
- [x] set the update key to the wipmetatimestamp 
- [x] use {db}/_all_docs for lookup

### CSV Error
- [x] Use regex sent by Russell to strip all mime types from data url
- [x] Ensure all filetypes can be uploaded

Notes: 
- Want to make the initialisation of the two swift containers in docker for dev?

**Comment by RussellMcOrmond** [comment]
Some additional notes:

### For dmdtask.storeAccess


You want to make a call to https://github.com/crkn-rcdr/Access-Platform/blob/main/services/couchdb/access/design/access/updates/forceUpdate.js once you have stored the metadata.  This is what triggers the processing so everything ends up on the patron sites.

I didn't note that in your checklist.



### For dmdtask.storePreservation

Look at http://iris.tor.c7a.ca:5984/_utils/#database/wipmeta/oocihm.8_01624 as a recent update they made using the old tool

* Has a label field that came from the metadata upload
* Has a dmd.xml attachment that came from the metadata upload.
* Has "updated": "2021-09-08T12:40:11Z"


The documents in that database have the AIP ID as the ID of the document, so the /{db}/_all_docs is all that is needed for bulk finding documents.

For changing the label I recommend creating a new design document managed within this repository, rather than using https://github.com/crkn-rcdr/cihm-ingestwip/blob/91c4df26c61d2f371630a14fc728a00d69fb2f2a/couchdb/wipmeta/design/tdr/updates/basic.js#L175-L179

Please use the string format for the date, and not the numeric, for the "updated" field.  The other tools that use this database can't parse it in the numeric format.
