### ISSUE TITLE
DMD Task file not uploading correctly

### ISSUE THREAD

**Issue by nataliemacdonald** [crkn-rcdr/Access-Platform#578]
DMD task id: aad3114f562cc11bbd2d83fb2551696e

Yesterday I tried to run a file of just under 10,000 records and it failed. Any way to see where it stopped so I can modify the file and start again?

**Comment by RussellMcOrmond** [comment]
While there is a bug in the front-end staff interface for @brittnylapierre to work on later so it doesn't output the generic "Something went wrong", I have set https://access.canadiana.ca/dmd/aad3114f562cc11bbd2d83fb2551696e to resume (directly in the database).

It was already at 98% stored when a network timeout happened. It was possible to hit resume and have the remaining items to store continue.

The last item I saw in the array was for https://www.canadiana.ca/view/oocihm.8_01922_12/1  , and it now displays the new label.


----


For discussing the future of the odd way "issues" of "series" are displayed, see: https://github.com/crkn-rcdr/cap/issues/138

The idea is to move away from displaying these as:
{label of parent} : {Label of issue}

to something that is more compatible with the IIIF data model, and a regular way of setting full rather than partial labels (or, generally, just using the title and not having to separately think about labels at all).
