### ISSUE TITLE
Restriction on decimal places after seconds in timestamps

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/Access-Platform#70]
I'm sorting through #55 and I have a question which I'm sure I've asked you before:

What part of our code can't handle the way JavaScript's `Date.prototype.toISOString()` creates a string with milliseconds specified? We strip them out in every update function that calls `new Date()`.

**Comment by RussellMcOrmond** [comment]
The Perl code, and the B-Tree lookup native to CouchDB (as used in the view).

The problem isn't that we have code that can't handle a date with miliseconds, but that we need to treat these things as strings that can be smaller, larger or **equal** and not as dates at all.

**Comment by SaschaAdler** [comment]
Two questions about your response, neither of which are meant to stake a position either way:

1. When it comes to finding an indexed date, does the B-tree have a harder time with strings that are identical, or strings that are still sorted correctly but have some longer stuff at the end? I imagine writing to the index might take a bit longer, but I don't know whether reading it, or presenting a sorted view, would.
2. What does it mean when these strings are _equal_?

We might as well store these as an integer with whatever precision we like, if we want to get the sorting right without worrying about format.

My motivation on bringing this up is just to ensure that we make writing design doc functions as unfussy as possible. I already suspect that the upgrade to SpiderMonkey in Couch 3 means that a lot of our design doc function hacks are no longer required.

**Comment by RussellMcOrmond** [comment]
The `nowdates` (`nowdate` as a string) in upudate functions is there to be common and not think about it, not specifically because it was needed for each specific database. The date functions in Perl didn't output miliseconds, so this meant that it didn't matter which language was used to generate a string from the current date, that the format of the string was the same.


We can spend time to confirm there are no issues now (to get rid of `.replace(/\..*Z/, "Z")` ? ), or we can wait to do that potential optimisation later.


1. I suspect the difference would be minimal, so not too worried about that.
2. For the use we have in these specific databases, we can avoid the issues in another way.

Using https://github.com/crkn-rcdr/Access-Platform/blob/main/Databases/internalmeta2/design/tdr/views/pressq.js as an example.

All we have to ensure is that when dates are compared in upd() that the concept of one date being larger than the other is clear.  I doubt we will have any issues there.

Where we had a problem with the format was for example https://github.com/crkn-rcdr/cihm-repomanage/blob/master/couchdb/tdrepo/design/tdr/views/adddate.js

I guess I'd be more comfortable thinking in the opposite order, which is that we verify we can treat the string as a parse-able date before we change the schema to require that we parse the string as a date.  Looking at the regexp it looks like it was written to support the milliseconds format anyway.

I'd have to look at some of the older Couch1 hacks to know if any of this matters any more.

**Comment by RussellMcOrmond** [comment]
Now that I've thought about it (I was avoiding doing that).

&lt;date&gt;T&lt;time&gt;Z

Where time is "hh:mm:ss" and date is "YYYY-MM-DD" is the most common over-the-wire way to indicate a GMT date-time.
Including anything smaller than seconds would cause extra storage/processing without providing us any value.  Given everything we do is multiplied by many millions in our databases, I think we should avoid storing things that don't provide us value.


Is it the aesthetic of the way we are deriving the date format that is the issue?

I went looking again for a cleaner way to turn off the milliseconds, but all the suggestions amount to the same thing (string manipulations to get rid of the '.' and the digits after). I tried `setMilliseconds(0)` and it merely output ".000" for that part.

```
var nowdates = nowdate.toISOString().replace(/\..*Z/, "Z");
var nowdates = nowdate.toISOString().replace(/\.\d+/, "");
var nowdates = nowdate.toISOString().split('.')[0]+"Z");
```

Personally I'd like to know if there is a way to do this in one line without creating the otherwise unused `nowdate` temporary variable.  I do want a variable and not to generate a new date each time I want to store a date, as there is value for any given update to always store the identical date.  While it may go away in the future, we currently have some larger update functions that can store 'now' many different times.

**Comment by SaschaAdler** [comment]
`const nowdates = (new Date()).toISOString().replace(/\.\d+/, "Z")` should work.

[`const` should work in Spidermonkey 60 (i.e. Firefox 60's JS engine)](https://caniuse.com/?compare=firefox+60&compareCats=JS), and I recommend that we use it (and `let` when necessary, which isn't frequent) instead of `var`.

I can edit the timestamp regex to disallow second fractions, also. I'm keen on thinking about using the Unix epoch (in seconds), instead of a string that is close to but not exactly conforming with RFC 3339, just to ensure that we mean exactly what we mean about what these are useful for. It's a minor quibble and the edited regex will suit me fine.

([RFC 3339](https://tools.ietf.org/html/rfc3339#section-5.6) is very cool with the optional second fractions, which is why I don't think code that processes them is a bad default.)

I have a slightly related question to this, but I'll create a new issue.
