### ISSUE TITLE
`_rev`, `updated`, and checking for conflicts

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/Access-Platform#72]
Admin tools are going to need to check that the source document for the data their working with hasn't changed since they fetched it from the database. We can use CouchDB's internal conflict checker to handle this, and at the very least, we can return an error to the user if the thing they're editing has been updated.

Does it make sense to use `updated`, which sporadically exists throughout our data, or a different, more expressive property to handle this? We could assign a name, email, and timestamp to every time the tool updates the object, kind of like what we were thinking for `dmdtask`.

**Comment by RussellMcOrmond** [comment]
a) We hadn't decided, just discussed.  I think a mini-project to do the second option would be ideal, given we can roll it out across more of the databases and tools if we put a focus on it for a time.

b) I'm not concerned about the security of staff updating through Sapindale.  I was wanting us to have an environment to test in where the 'work was console.log() rather than doing any database updates.   Thinking last night, doing a smelt of an ID that has already been smelted accomplishes the same thing (IE: gives an error, and doesn't update anything).   The underlying problem for testing is that we have a way to create manifests, but not yet the tools to easily manage them (remove unused ones, change slugs, etc).

**Comment by SaschaAdler** [comment]
I think we're primarily discussing this in #83, and so I'll close this issue.
